version: '3'
services: 
  feims:
    image: ujere/lexington:feims
    volumes: 
      - siteNode:/app/
    depends_on: 
      - database
    ports: 
      - "5500:5500" 
volumes: 
    siteDb:
    siteNode:

